id = "please-build"
name = "Please Build"
version = "0.2.1"
schema_version = 1
authors = ["nskalski"]
description = "Syntax highlighting and LSP support for the Please build system"
repository = "https://github.com/nskalski/zed-please"

[grammars.please]
repository = "file:///home/nskalski/zedplug/zed-please"
rev = "6b0579830c2673fb8dfb1f19df68711d5a4bf275"

[language_servers.build-langserver]
name = "Please Build Language Server"
languages = ["Please Build"]
