id = "please-build"
name = "Please Build"
version = "0.2.1"
schema_version = 1
authors = ["nskalski"]
description = "Syntax highlighting and LSP support for the Please build system"
repository = "https://github.com/nskalski/zed-please"

[grammars.please]
repository = "file:///home/nskalski/zedplug/zed-please"
rev = "812bee0967b2eaf2b945fad705b5a5b083119da0"

[language_servers.build-langserver]
name = "Please Build Language Server"
languages = ["Please Build"]
