id = "please-build"
name = "Please Build"
version = "0.2.1"
schema_version = 1
authors = ["nskalski"]
description = "Syntax highlighting and LSP support for the Please build system"
repository = "https://github.com/nskalski/zed-please"

[grammars.please]
repository = "file:///home/nskalski/zedplug/zed-please"
rev = "a8ca866323772a4880eafa733fa168e4c05765c2"

[language_servers.build-langserver]
name = "Please Build Language Server"
languages = ["Please Build"]
